# Funding configuration
# Used to display sponsor button in repository

github: # Replace with GitHub Sponsors username if available
patreon: # Replace with Patreon username if available
ko_fi: # Replace with Ko-fi username if available
custom: # Add custom funding link if available
